const $ = (s) => document.querySelector(s);
const state = { image: null, imagePath: null, rows: [], folder: null, selected: 0, zoom: 1, fields: [
  { name: 'Campo 1', enabled: true, sample: 'Nome e Cognome', font: 'Georgia', size: 42, color: '#20243a', align: 'center', x: 50, y: 50 },
  { name: 'Campo 2', enabled: false, sample: 'Titolo / Corso', font: 'Arial', size: 22, color: '#20243a', align: 'center', x: 50, y: 60 },
  { name: 'Campo 3', enabled: false, sample: 'Data / Informazioni', font: 'Arial', size: 16, color: '#20243a', align: 'center', x: 50, y: 70 }
] };
let fonts = ['Arial','Georgia','Times New Roman','Verdana','Trebuchet MS','Courier New','Impact'];
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 3200); }
function renderFields() { $('#fields').innerHTML = state.fields.map((f,i) => `<div class="field-card ${state.selected===i?'selected':''}" data-field="${i}"><div class="field-top"><input class="enabled" type="checkbox" ${f.enabled?'checked':''}><span class="field-name">${f.name}</span></div><input class="sample" value="${esc(f.sample)}" placeholder="Testo di esempio"><div class="settings"><select class="font">${fonts.map(x=>`<option ${x===f.font?'selected':''}>${x}</option>`).join('')}</select><input class="size" type="number" min="6" max="300" value="${f.size}" title="Dimensione"><input class="color" type="color" value="${f.color}" title="Colore"></div><div class="align">${[['left','≡'],['center','≡'],['right','≡']].map(([x,label])=>`<button class="al ${f.align===x?'active':''}" data-align="${x}" title="Allinea ${x}">${label}</button>`).join('')}</div></div>`).join('');
  document.querySelectorAll('.field-card').forEach(card => { const i=+card.dataset.field, f=state.fields[i]; card.addEventListener('click',e=>{if(!e.target.matches('input,select,button')) {state.selected=i;renderFields();renderOverlays();}}); card.querySelector('.enabled').onchange=e=>{f.enabled=e.target.checked;renderOverlays();}; card.querySelector('.sample').oninput=e=>{f.sample=e.target.value;renderOverlays();}; card.querySelector('.font').onchange=e=>{f.font=e.target.value;renderOverlays();}; card.querySelector('.size').onchange=e=>{f.size=Math.max(6,+e.target.value||6);renderOverlays();}; card.querySelector('.color').oninput=e=>{f.color=e.target.value;renderOverlays();}; card.querySelectorAll('.al').forEach(b=>b.onclick=()=>{f.align=b.dataset.align;renderFields();renderOverlays();}); }); }
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');}
function renderOverlays() { const box=$('#overlays'); box.innerHTML=''; state.fields.forEach((f,i)=>{if(!f.enabled)return;const el=document.createElement('div');el.className='overlay '+(state.selected===i?'selected':'');el.dataset.field=i;el.textContent=f.sample || f.name;Object.assign(el.style,{left:f.x+'%',top:f.y+'%',fontFamily:f.font,fontSize:scaledSize(f.size)+'px',color:f.color,textAlign:f.align,transform:f.align==='center'?'translate(-50%,-50%)':f.align==='right'?'translate(-100%,-50%)':'translate(0,-50%)'});el.addEventListener('pointerdown',startDrag);el.addEventListener('click',()=>{state.selected=i;renderFields();renderOverlays();});box.append(el);}); }
function scaledSize(size){const img=$('#template'); return img.naturalWidth ? Math.max(8,size*(img.clientWidth/img.naturalWidth)) : size;}
function startDrag(e){e.preventDefault();const i=+e.currentTarget.dataset.field,stage=$('#stage');state.selected=i;renderFields();const move=ev=>{const r=stage.getBoundingClientRect();state.fields[i].x=Math.max(0,Math.min(100,(ev.clientX-r.left)/r.width*100));state.fields[i].y=Math.max(0,Math.min(100,(ev.clientY-r.top)/r.height*100));renderOverlays();};const end=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);}
async function chooseTemplate(){const p=await window.diplomi.pickFile([{name:'Immagini',extensions:['png','jpg','jpeg','webp']}]);if(!p)return;const bytes=await window.diplomi.readFile(p);const blob=new Blob([bytes]);state.image=await createImageBitmap(blob);state.imagePath=p;$('#template').src=URL.createObjectURL(blob);$('#templateName').textContent=p.split(/[\\/]/).pop();$('#template').onload=()=>{ $('#empty').classList.add('hidden');$('#stage').classList.remove('hidden');renderOverlays();refreshGenerate();};}
async function chooseData(){const p=await window.diplomi.pickFile([{name:'Dati CSV o Excel',extensions:['csv','xlsx','xls']}]);if(!p)return;const bytes=await window.diplomi.readFile(p);try{const wb=XLSX.read(bytes,{type:'array'});const data=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});state.rows=data.map(r=>[r.campo1??r.Campo1??r['Campo 1']??'',r.campo2??r.Campo2??r['Campo 2']??'',r.campo3??r.Campo3??r['Campo 3']??'']);if(!state.rows.length)throw new Error();$('#dataName').textContent=`${p.split(/[\\/]/).pop()} · ${state.rows.length} righe`;$('#dataPreview').textContent=state.rows.slice(0,3).map((r,i)=>`${i+1}. ${r.filter(Boolean).join(' · ')}`).join('\n')+(state.rows.length>3?'\n…':'');refreshGenerate();}catch{toast('Impossibile leggere il file dati. Verifica le intestazioni campo1, campo2, campo3.');}}
async function downloadTemplate(type){const rows=[['campo1','campo2','campo3'],['Mario Rossi','Corso di Excel','23 luglio 2026'],['Giulia Bianchi','Corso di Excel','23 luglio 2026']];let base64,name;if(type==='csv'){base64=btoa(unescape(encodeURIComponent(rows.map(r=>r.map(v=>`"${v}"`).join(',')).join('\r\n'))));name='modello-diplomi.csv';}else{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'Diplomi');base64=XLSX.write(wb,{bookType:'xlsx',type:'base64'});name='modello-diplomi.xlsx';}const saved=await window.diplomi.saveFile(name,base64);if(saved)toast('Modello salvato: '+saved.split(/[\\/]/).pop());}
async function chooseFolder(){const p=await window.diplomi.pickFolder();if(!p)return;state.folder=p;$('#folderName').textContent=p;refreshGenerate();}
function refreshGenerate(){$('#generate').disabled=!(state.image&&state.rows.length&&state.folder);}
function drawText(ctx,text,f,scale){ctx.save();ctx.font=`${f.size*scale}px ${f.font}`;ctx.fillStyle=f.color;ctx.textBaseline='middle';ctx.textAlign=f.align;ctx.fillText(String(text||''),f.x/100*state.image.width,f.y/100*state.image.height);ctx.restore();}
async function generate(){const button=$('#generate');button.disabled=true;button.textContent='GENERAZIONE…';try{const canvas=document.createElement('canvas');canvas.width=state.image.width;canvas.height=state.image.height;const ctx=canvas.getContext('2d');const images=[];for(let i=0;i<state.rows.length;i++){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(state.image,0,0);state.fields.forEach((f,n)=>{if(f.enabled)drawText(ctx,state.rows[i][n]||'',f,1);});images.push({name:state.rows[i][0]||`diploma_${i+1}`,dataUrl:canvas.toDataURL('image/png')});}const count=await window.diplomi.saveImages(state.folder,images);toast(`${count} immagini create nella cartella selezionata.`);}catch(e){console.error(e);toast('Errore durante la generazione.');}finally{button.innerHTML='<span>✦</span> GENERA IMMAGINI';refreshGenerate();}}
$('#chooseTemplate').onclick=chooseTemplate;$('#chooseData').onclick=chooseData;$('#downloadCsv').onclick=()=>downloadTemplate('csv');$('#downloadXlsx').onclick=()=>downloadTemplate('xlsx');$('#chooseFolder').onclick=chooseFolder;$('#generate').onclick=generate;$('#zoomIn').onclick=()=>setZoom(.1);$('#zoomOut').onclick=()=>setZoom(-.1);function setZoom(delta){state.zoom=Math.max(.5,Math.min(1.5,state.zoom+delta));$('#stage').style.transform=`scale(${state.zoom})`;$('#zoomLabel').textContent=Math.round(state.zoom*100)+'%';}
renderFields();
window.diplomi.getSystemFonts().then(systemFonts=>{if(systemFonts.length){fonts=[...new Set([...fonts,...systemFonts])].sort((a,b)=>a.localeCompare(b));renderFields();}}).catch(()=>{});
